nginx:
  build: ./nginx/
  ports:
    - "80:80"
  links:
    - es:es
  volumes_from:
    - data

es:
  build: ./es/
  volumes_from:
    - data

data:
  image: busybox
  command: /bin/true
  volumes:
    - /var/docker:/data
