hodavidhara:
  build: ../app/

nginx:
  build: ./nginx/
  ports:
    - "80:80"
  links:
    - es:es
    - hodavidhara:hodavidhara
  volumes_from:
    - data

es:
  build: ./es/
  volumes_from:
    - data

data:
  build: ./es/
  command: /bin/true
  volumes:
    - /data/es
