app:
  build: ../app/
  restart: always
  volumes:
    - /opt/code
  volumes_from:
    - data

nginx:
  build: ./nginx/
  restart: always
  ports:
    - "80:80"
  links:
    - es:es
    - app:app
  volumes_from:
    - data
    - app

es:
  build: ./es/
  restart: always
  environment:
    - ES_HEAP_SIZE=128m
  volumes_from:
    - data

data:
  image: busybox
  command: /bin/true
  volumes:
    - /usr/share/elasticsearch/config
