version: '2'
services:
  app:
    build: ../app/
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /opt/code

  nginx:
    build: ./nginx/
    restart: always
    ports:
      - "80:80"
    links:
      - es:es
      - app:app
    volumes_from:
      - app

  es:
    build: ./es/
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_HEAP_SIZE=128m
    volumes:
      - /usr/share/elasticsearch/config
    network_mode: "host"