app:
  build: ../app/
  restart: always

nginx:
  build: ./nginx/
  restart: always
  ports:
    - "80:80"
  links:
    - es:es
    - app:app
  volumes_from:
    - data

es:
  build: ./es/
  restart: always
  volumes_from:
    - data

data:
  build: ./es/
  command: /bin/true
  volumes:
    - /usr/share/elasticsearch/config
